CREATE TABLE IF NOT EXISTS `verification_report` (
  `vfi_rpt_id` int NOT NULL AUTO_INCREMENT,
  `vfi_rpt_term_device_id` text NOT NULL,
  `vfi_rpt_term_serial_num` text NOT NULL,
  `vfi_rpt_term_product_num` text NOT NULL,
  `vfi_rpt_term_model` text NOT NULL,
  `vfi_rpt_term_app_name` text NOT NULL,
  `vfi_rpt_term_app_version` text NOT NULL,
  `vfi_rpt_term_parameter` text NOT NULL,
  `vfi_rpt_term_tms_create_operator` text NOT NULL,
  `vfi_rpt_term_tms_create_dt_operator` datetime NOT NULL,
  `vfi_rpt_tech_name` varchar(150) NOT NULL,
  `vfi_rpt_tech_nip` varchar(50) NOT NULL,
  `vfi_rpt_tech_number` varchar(100) NOT NULL,
  `vfi_rpt_tech_address` text NOT NULL,
  `vfi_rpt_tech_company` varchar(100) NOT NULL,
  `vfi_rpt_tech_sercive_point` varchar(100) NOT NULL,
  `vfi_rpt_tech_phone` varchar(15) NOT NULL,
  `vfi_rpt_tech_gender` varchar(25) NOT NULL,
  `vfi_rpt_ticket_no` varchar(50) NOT NULL,
  `vfi_rpt_spk_no` varchar(50) NOT NULL,
  `vfi_rpt_work_order` varchar(50) NOT NULL,
  `vfi_rpt_remark` varchar(200) NOT NULL,
  `vfi_rpt_status` varchar(10) NOT NULL,
  `created_by` varchar(100) NOT NULL,
  `created_dt` datetime NOT NULL,
  PRIMARY KEY (`vfi_rpt_id`),
  UNIQUE KEY `vfi_rpt_id` (`vfi_rpt_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
