-- Seed FAQ data from veristoreTools2 (idempotent: skips if table already has data).
INSERT INTO `faq` (`faq_id`, `faq_parent`, `faq_seq`, `faq_privileges`, `faq_name`, `faq_link`)
SELECT v.* FROM (
  SELECT 1 as faq_id, NULL as faq_parent, 0 as faq_seq, 'ADMIN' as faq_privileges, 'Pengantar' as faq_name, '1' as faq_link UNION ALL
  SELECT 2,NULL,1,'ADMIN','Login',NULL UNION ALL
  SELECT 3,2,0,'ADMIN','Login Administrator','2-3' UNION ALL
  SELECT 4,NULL,3,'ADMIN','Pengguna',NULL UNION ALL
  SELECT 5,4,0,'ADMIN','Tambah Pengguna','4-5' UNION ALL
  SELECT 6,4,1,'ADMIN','Edit Pengguna','4-6' UNION ALL
  SELECT 7,NULL,4,'ADMIN','Aktifitas',NULL UNION ALL
  SELECT 8,7,0,'ADMIN','Search Aktifitas','7-8' UNION ALL
  SELECT 9,NULL,5,'ADMIN','Sinkronisasi CSI','9' UNION ALL
  SELECT 10,9,0,'ADMIN','Penjadwalan','9-10' UNION ALL
  SELECT 11,10,0,'ADMIN','Penjadwalan TIAP JAM','10-11' UNION ALL
  SELECT 12,10,1,'ADMIN','Penjadwalan HARIAN','10-12' UNION ALL
  SELECT 13,10,2,'ADMIN','Penjadwalan MINGGUAN','10-13' UNION ALL
  SELECT 14,9,1,'ADMIN','Manual','9-14' UNION ALL
  SELECT 15,14,0,'ADMIN','Search Sinkronisasi Data CSI','14-15' UNION ALL
  SELECT 16,NULL,6,'ADMIN','Data CSI',NULL UNION ALL
  SELECT 17,16,0,'ADMIN','Search Data CSI','16-17' UNION ALL
  SELECT 18,NULL,7,'ADMIN','Teknisi',NULL UNION ALL
  SELECT 19,18,0,'ADMIN','Tambah Teknisi','18-19' UNION ALL
  SELECT 20,18,1,'ADMIN','Edit Teknisi','18-20' UNION ALL
  SELECT 21,NULL,8,'ADMIN','Verifikasi','21' UNION ALL
  SELECT 22,NULL,9,'ADMIN','Laporan Verifikasi','22' UNION ALL
  SELECT 23,NULL,10,'ADMIN','About','23' UNION ALL
  SELECT 24,NULL,0,'OPERATOR','Pengantar','1' UNION ALL
  SELECT 25,NULL,1,'OPERATOR','Login',NULL UNION ALL
  SELECT 26,25,0,'OPERATOR','Login Operator','25-26' UNION ALL
  SELECT 27,NULL,3,'OPERATOR','Sinkronisasi CSI','9' UNION ALL
  SELECT 28,27,0,'OPERATOR','Manual','9-14' UNION ALL
  SELECT 29,28,0,'OPERATOR','Search Sinkronisasi Data CSI','14-15' UNION ALL
  SELECT 30,NULL,4,'OPERATOR','Data CSI',NULL UNION ALL
  SELECT 31,30,0,'OPERATOR','Search Data CSI','16-17' UNION ALL
  SELECT 32,NULL,5,'OPERATOR','Verifikasi','21' UNION ALL
  SELECT 33,NULL,6,'OPERATOR','About','23' UNION ALL
  SELECT 34,NULL,2,'ADMIN','Veristore Dashboard','34' UNION ALL
  SELECT 35,NULL,2,'OPERATOR','Veristore Dashboard','34' UNION ALL
  SELECT 36,NULL,0,'TMS ADMIN','Pengantar','36' UNION ALL
  SELECT 37,NULL,0,'','',NULL UNION ALL
  SELECT 38,NULL,1,'TMS ADMIN','Login','37-38' UNION ALL
  SELECT 39,NULL,2,'TMS ADMIN','Veristore Dashboard','39' UNION ALL
  SELECT 40,NULL,3,'TMS ADMIN','Pengguna',NULL UNION ALL
  SELECT 41,40,0,'TMS ADMIN','Tambah Pengguna','40-41' UNION ALL
  SELECT 42,40,1,'TMS ADMIN','Edit Pengguna','40-42' UNION ALL
  SELECT 43,NULL,0,'','',NULL UNION ALL
  SELECT 44,NULL,4,'TMS ADMIN','Aktifitas','43-44' UNION ALL
  SELECT 45,NULL,6,'TMS ADMIN','CSI','45' UNION ALL
  SELECT 46,45,0,'TMS ADMIN','Login','45-46' UNION ALL
  SELECT 47,45,1,'TMS ADMIN','Add','45-47' UNION ALL
  SELECT 48,45,2,'TMS ADMIN','Import','45-48' UNION ALL
  SELECT 49,45,3,'TMS ADMIN','Copy','45-49' UNION ALL
  SELECT 50,45,4,'TMS ADMIN','Edit','45-50' UNION ALL
  SELECT 51,45,5,'TMS ADMIN','Update','45-51' UNION ALL
  SELECT 52,45,6,'TMS ADMIN','Search','45-52' UNION ALL
  SELECT 53,45,7,'TMS ADMIN','Delete','45-53' UNION ALL
  SELECT 54,NULL,7,'TMS ADMIN','About','54' UNION ALL
  SELECT 55,NULL,0,'TMS OPERATOR','Pengantar','55' UNION ALL
  SELECT 56,NULL,0,'','',NULL UNION ALL
  SELECT 57,NULL,1,'TMS OPERATOR','Login','56-57' UNION ALL
  SELECT 58,NULL,2,'TMS OPERATOR','Veristore Dashboard','58' UNION ALL
  SELECT 59,NULL,4,'TMS OPERATOR','CSI','59' UNION ALL
  SELECT 60,59,0,'TMS OPERATOR','Login CSI','59-60' UNION ALL
  SELECT 61,59,1,'TMS OPERATOR','Add CSI','59-61' UNION ALL
  SELECT 62,59,2,'TMS OPERATOR','Import CSI','59-62' UNION ALL
  SELECT 63,59,3,'TMS OPERATOR','Copy CSI','59-63' UNION ALL
  SELECT 64,59,4,'TMS OPERATOR','Edit CSI','59-64' UNION ALL
  SELECT 65,59,5,'TMS OPERATOR','Update CSI','59-65' UNION ALL
  SELECT 66,59,6,'TMS OPERATOR','Search CSI','59-66' UNION ALL
  SELECT 67,NULL,5,'TMS OPERATOR','About','67' UNION ALL
  SELECT 68,NULL,5,'TMS ADMIN','Merchant',NULL UNION ALL
  SELECT 69,68,0,'TMS ADMIN','Merchant Management','69' UNION ALL
  SELECT 70,69,0,'TMS ADMIN','Login Merchant Management','69-70' UNION ALL
  SELECT 71,69,1,'TMS ADMIN','Add Merchant Management','69-71' UNION ALL
  SELECT 72,69,2,'TMS ADMIN','Edit Merchant Management','69-72' UNION ALL
  SELECT 73,69,3,'TMS ADMIN','Delete Merchant Management','69-73' UNION ALL
  SELECT 74,69,4,'TMS ADMIN','Search Merchant Management','69-74' UNION ALL
  SELECT 75,68,1,'TMS ADMIN','Group Management','75' UNION ALL
  SELECT 76,75,0,'TMS ADMIN','Login Group Management','75-76' UNION ALL
  SELECT 77,75,1,'TMS ADMIN','Add Group Management','75-77' UNION ALL
  SELECT 78,75,2,'TMS ADMIN','Edit Group Management','75-78' UNION ALL
  SELECT 79,75,3,'TMS ADMIN','Delete Group Management','75-79' UNION ALL
  SELECT 80,75,4,'TMS ADMIN','Search Group Management','75-80' UNION ALL
  SELECT 81,NULL,3,'TMS OPERATOR','Merchant',NULL UNION ALL
  SELECT 82,81,0,'TMS OPERATOR','Merchant Management','' UNION ALL
  SELECT 83,82,0,'TMS OPERATOR','Login','' UNION ALL
  SELECT 84,82,1,'TMS OPERATOR','Add','' UNION ALL
  SELECT 85,82,2,'TMS OPERATOR','Edit','' UNION ALL
  SELECT 86,82,3,'TMS OPERATOR','Search','' UNION ALL
  SELECT 87,81,1,'TMS OPERATOR','Group Management','' UNION ALL
  SELECT 88,87,0,'TMS OPERATOR','Login','' UNION ALL
  SELECT 89,87,1,'TMS OPERATOR','Add','' UNION ALL
  SELECT 90,87,2,'TMS OPERATOR','Edit','' UNION ALL
  SELECT 91,87,3,'TMS OPERATOR','Search','' UNION ALL
  SELECT 92,NULL,0,'TMS SUPERVISOR','Pengantar','' UNION ALL
  SELECT 93,NULL,1,'TMS SUPERVISOR','Login',NULL UNION ALL
  SELECT 94,93,0,'TMS SUPERVISOR','Login TMS Supervisor','' UNION ALL
  SELECT 95,NULL,2,'TMS SUPERVISOR','Veristore Dashboard','' UNION ALL
  SELECT 96,NULL,3,'TMS SUPERVISOR','Aktifitas',NULL UNION ALL
  SELECT 97,96,0,'TMS SUPERVISOR','Search Aktifitas','' UNION ALL
  SELECT 98,NULL,4,'TMS SUPERVISOR','Merchant',NULL UNION ALL
  SELECT 99,98,0,'TMS SUPERVISOR','Merchant Management','' UNION ALL
  SELECT 100,99,0,'TMS SUPERVISOR','Login','' UNION ALL
  SELECT 101,99,1,'TMS SUPERVISOR','Search','' UNION ALL
  SELECT 102,98,1,'TMS SUPERVISOR','Group Management','' UNION ALL
  SELECT 103,102,0,'TMS SUPERVISOR','Login','' UNION ALL
  SELECT 104,102,1,'TMS SUPERVISOR','Search','' UNION ALL
  SELECT 105,NULL,5,'TMS SUPERVISOR','CSI','' UNION ALL
  SELECT 106,105,0,'TMS SUPERVISOR','Login','' UNION ALL
  SELECT 107,105,1,'TMS SUPERVISOR','View','' UNION ALL
  SELECT 108,105,2,'TMS SUPERVISOR','Search','' UNION ALL
  SELECT 109,NULL,6,'TMS SUPERVISOR','About',''
) v WHERE NOT EXISTS (SELECT 1 FROM `faq` LIMIT 1);
