package queue

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"math/rand"
	"regexp"
	"sort"
	"strconv"
	"strings"
	gosync "sync"
	"sync/atomic"
	"time"

	"github.com/hibiken/asynq"
	"github.com/rs/zerolog"
	"github.com/rs/zerolog/log"
	"github.com/xuri/excelize/v2"
	"gorm.io/gorm"

	"github.com/verifone/veristoretools3/internal/admin"
	"github.com/verifone/veristoretools3/internal/terminal"
	"github.com/verifone/veristoretools3/internal/tms"
)

const (
	// syncWorkerCount is the number of concurrent workers for fetching
	// terminal parameters. Each worker fetches 8 tabs sequentially (1 API
	// call at a time). 25 workers = ~25 concurrent TMS calls — avoids
	// overwhelming the TMS server while keeping it busy.
	// (50 workers caused 10-15s API responses; fewer workers get 2-3s each.)
	syncWorkerCount = 25
)

// SyncParameterPayload is the JSON payload for the sync:parameter task.
// Chained from report:terminal when TriggerSync is true (Sekarang button).
type SyncParameterPayload struct {
	ReportName string `json:"report_name"`
	Session    string `json:"session"`
	UserID     int    `json:"user_id"`
	UserName   string `json:"user_name"`
	AppID      string `json:"app_id"`
	AppName    string `json:"app_name"`
	AppVersion string `json:"app_version"`
	IsPartial  bool   `json:"is_partial,omitempty"`
}

// syncTerminalRow holds data parsed from one row of the Excel report.
type syncTerminalRow struct {
	Index      int
	CSI        string // Column A (deviceId / serial num used as key)
	SN         string // Column B
	PN         string // Column C
	Model      string // Column D
	Merchant   string // Column E
	AppVersion string // Column G (actual installed version per terminal)
	AppID      string // Column H (appId for this terminal's version)
}

// SyncParameterHandler reads the Excel report generated by report:terminal,
// fetches terminal parameters from the TMS API for each terminal, and updates
// the local terminal and terminal_parameter tables. This is the Go equivalent
// of veristoreTools2's SyncTerminalParameter.php component, optimized with a
// 50-worker concurrent pool instead of V2's sequential approach.
type SyncParameterHandler struct {
	tmsService *tms.Service
	tmsClient  *tms.Client
	termRepo   *terminal.Repository
	adminRepo  *admin.Repository
	db         *gorm.DB
}

// NewSyncParameterHandler creates a new handler for the sync:parameter task.
func NewSyncParameterHandler(
	tmsService *tms.Service,
	tmsClient *tms.Client,
	termRepo *terminal.Repository,
	adminRepo *admin.Repository,
	_ interface{}, // syncRepo — kept for backward-compatible constructor signature
	db *gorm.DB,
	_ int, // batchSize — no longer used
) *SyncParameterHandler {
	return &SyncParameterHandler{
		tmsService: tmsService,
		tmsClient:  tmsClient,
		termRepo:   termRepo,
		adminRepo:  adminRepo,
		db:         db,
	}
}

// ProcessTask implements asynq.Handler. It:
//  1. Reads the Excel report from the tms_report table.
//  2. Parses terminal rows from the spreadsheet.
//  3. For each terminal, fetches parameters from TMS via a 50-worker pool.
//  4. Updates the local terminal and terminal_parameter tables.
//  5. Updates sync_terminal progress and marks complete.
func (h *SyncParameterHandler) ProcessTask(ctx context.Context, task *asynq.Task) error {
	var payload SyncParameterPayload
	if err := json.Unmarshal(task.Payload(), &payload); err != nil {
		return fmt.Errorf("sync_parameter: unmarshal payload: %w", err)
	}

	logger := log.With().Str("task", TaskSyncParameter).Str("report", payload.ReportName).Logger()
	logger.Info().Msg("starting parameter sync job")
	jobStartTime := time.Now()

	// Log job start to queue_log.
	createTime := strconv.FormatInt(time.Now().UnixMilli(), 10)
	_ = h.adminRepo.CreateQueueLog(&admin.QueueLog{
		CreateTime:  createTime,
		ExecTime:    createTime,
		ProcessName: "SYNC",
		ServiceName: strPtr("sync:parameter"),
	})

	session := payload.Session
	if session == "" {
		session = h.tmsService.GetSession()
	}
	if session == "" {
		h.adminRepo.FailPendingSyncs(payload.UserID)
		return fmt.Errorf("sync_parameter: no active TMS session")
	}

	// ------------------------------------------------------------------
	// Phase 1: Read Excel report from tms_report table.
	// ------------------------------------------------------------------
	var allTMSCount int64
	var deleted int64
	var successCount int64
	var totalTerminals int
	syncStartTime := time.Now()

	if payload.ReportName == "" {
		logger.Info().Msg("no report to parse — skipping Phase 1 & 2, running Phase 3 & 4 only")
	} else {

	report, err := h.adminRepo.FindTmsReportByName(payload.ReportName)
	if err != nil || report == nil {
		h.adminRepo.FailPendingSyncs(payload.UserID)
		return fmt.Errorf("sync_parameter: report not found: %s: %w", payload.ReportName, err)
	}

	if len(report.TmsRptFile) == 0 {
		h.adminRepo.FailPendingSyncs(payload.UserID)
		return fmt.Errorf("sync_parameter: report file is empty: %s", payload.ReportName)
	}

	// Parse the Excel file.
	f, err := excelize.OpenReader(bytes.NewReader(report.TmsRptFile))
	if err != nil {
		h.adminRepo.FailPendingSyncs(payload.UserID)
		return fmt.Errorf("sync_parameter: open excel: %w", err)
	}
	defer f.Close()

	// Get the first sheet name.
	sheetName := f.GetSheetName(0)
	if sheetName == "" {
		h.adminRepo.FailPendingSyncs(payload.UserID)
		return fmt.Errorf("sync_parameter: no sheets in excel")
	}

	// Parse appID from row 1 cell A1 ("APPID:{id}").
	appID := payload.AppID
	if appID == "" {
		a1, _ := f.GetCellValue(sheetName, "A1")
		if strings.HasPrefix(a1, "APPID:") {
			appID = strings.TrimPrefix(a1, "APPID:")
		}
	}

	// Read all rows. Row 1 = APPID header, Row 2 = column headers, Row 3+ = data.
	allRows, err := f.GetRows(sheetName)
	if err != nil {
		h.adminRepo.FailPendingSyncs(payload.UserID)
		return fmt.Errorf("sync_parameter: read rows: %w", err)
	}

	var terminals []syncTerminalRow
	for i, row := range allRows {
		if i < 2 { // Skip header rows
			continue
		}
		if len(row) < 2 { // Need at least CSI and SN
			continue
		}

		csi := ""
		sn := ""
		pn := ""
		model := ""
		merchant := ""
		appVersion := ""
		termAppID := ""
		if len(row) > 0 {
			csi = strings.TrimSpace(row[0])
		}
		if len(row) > 1 {
			sn = strings.TrimSpace(row[1])
		}
		if len(row) > 2 {
			pn = strings.TrimSpace(row[2])
		}
		if len(row) > 3 {
			model = strings.TrimSpace(row[3])
		}
		if len(row) > 4 {
			merchant = strings.TrimSpace(row[4])
		}
		// Column G: per-terminal AppVersion, Column H: per-terminal AppID
		if len(row) > 6 {
			appVersion = strings.TrimSpace(row[6])
		}
		if len(row) > 7 {
			termAppID = strings.TrimSpace(row[7])
		}

		if sn == "" && csi == "" {
			continue
		}

		terminals = append(terminals, syncTerminalRow{
			Index:      len(terminals),
			CSI:        csi,
			SN:         sn,
			PN:         pn,
			Model:      model,
			Merchant:   merchant,
			AppVersion: appVersion,
			AppID:      termAppID,
		})
	}

	totalTerminals := len(terminals)
	logger.Info().Int("total_terminals", totalTerminals).Str("sheet", sheetName).Msg("parsed Excel report")

	if totalTerminals == 0 {
		logger.Warn().Msg("no terminals in report, completing sync")
		h.adminRepo.CompletePendingSyncs(payload.UserID)
		return nil
	}

	// ------------------------------------------------------------------
	// Phase 2: Fetch parameters and update local DB using worker pool.
	// Uses incremental create/update per terminal.
	// Each terminal's parameters are deleted and recreated individually
	// inside updateLocalTerminal.
	// Phase 3 (after workers finish) removes any local terminals
	// that are no longer in the TMS report (e.g. deleted from TMS).
	// ------------------------------------------------------------------
	tabNames := tms.GetAllTabNames(h.db)
	// Fetch operationMark once — it's session-level, same for all terminals.
	operationMark, err := h.tmsClient.GetOperationMark(session)
	if err != nil {
		logger.Warn().Err(err).Msg("failed to get operation mark, sync may be incomplete")
	}
	logger.Info().Int("tabs", len(tabNames)).Msg("cached tab names and operation mark for sync")

	// ---- Bulk-fetch all TMS terminal IDs in 2-3 API calls ----
	// This replaces 559 individual getIdFromSN calls (~300ms each) with a
	// single bulk operation (~1s total), saving ~17 seconds.
	bulkStart := time.Now()
	idMap, err := h.tmsClient.BulkFetchTerminalIds(session)
	if err != nil {
		logger.Warn().Err(err).Msg("bulk ID fetch failed, will fall back to per-terminal lookup")
		idMap = nil
	} else {
		logger.Info().Int("fetched", len(idMap)).Str("elapsed", time.Since(bulkStart).Round(time.Millisecond).String()).Msg("bulk-fetched terminal IDs")
	}

	jobs := make(chan syncTerminalRow, totalTerminals)
	var processedCount int64
	var successCount int64
	var wg gosync.WaitGroup

	// Cancellation channel: closed when sync is reset/cancelled by user.
	cancelCh := make(chan struct{})
	go func() {
		ticker := time.NewTicker(3 * time.Second)
		defer ticker.Stop()
		for {
			select {
			case <-ctx.Done():
				return
			case <-cancelCh:
				return
			case <-ticker.C:
				if h.adminRepo.IsSyncCancelled(payload.UserID) {
					logger.Info().Msg("sync cancelled by user (sync reset)")
					close(cancelCh)
					return
				}
			}
		}
	}()

	phase2Start := time.Now()

	for w := 0; w < syncWorkerCount; w++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for t := range jobs {
				select {
				case <-ctx.Done():
					return
				case <-cancelCh:
					return
				default:
				}

				serialNum := t.SN
				if serialNum == "" || serialNum == "<nil>" || serialNum == t.CSI {
					// Don't use CSI name as hardware SN — leave empty if TMS
					// returns no distinct SN (common for newly imported terminals).
					serialNum = ""
				}

				// Use per-terminal AppID if available (from Excel column H),
				// otherwise fall back to the report-level appID.
				termAppID := t.AppID
				if termAppID == "" || termAppID == "0" || termAppID == "<nil>" {
					termAppID = appID
				}

				// Use per-terminal AppVersion if available (from Excel column G),
				// otherwise fall back to the payload version.
				termAppVersion := t.AppVersion
				if termAppVersion == "" || termAppVersion == "<nil>" {
					termAppVersion = payload.AppVersion
				}

				// Fetch terminal parameters from TMS using cached operationMark
				// and concurrent tab fetching for speed.
				// Use CSI (Column A = TMS deviceId) for the TMS lookup.
				tmsDeviceId := t.CSI
				if tmsDeviceId == "" {
					tmsDeviceId = serialNum
				}
				var paramResp *tms.TMSResponse
				apiStart := time.Now()
				usedBulk := false
				if termAppID != "" && tmsDeviceId != "" && operationMark != "" {
					// Try pre-resolved ID from bulk fetch (O(1) map lookup).
					// Falls back to individual API call only if bulk fetch missed this terminal.
					var resp *tms.TMSResponse
					var fetchErr error
					if idMap != nil {
						if termId, ok := idMap[tmsDeviceId]; ok && termId > 0 {
							usedBulk = true
							resp, fetchErr = h.tmsClient.FetchParameterTabsForId(session, termId, termAppID, tabNames, operationMark)
						} else {
							// Not in bulk map — fall back to individual lookup.
							resp, fetchErr = h.tmsClient.GetTerminalParameterMultiTabCached(session, tmsDeviceId, termAppID, tabNames, operationMark)
						}
					} else {
						// Bulk fetch failed entirely — use original per-terminal lookup.
						resp, fetchErr = h.tmsClient.GetTerminalParameterMultiTabCached(session, tmsDeviceId, termAppID, tabNames, operationMark)
					}

					if fetchErr == nil && resp != nil && resp.ResultCode == 0 && resp.Data != nil {
						if pl, ok := resp.Data["paraList"].([]interface{}); ok && len(pl) > 0 {
							paramResp = resp
						}
					}
					if paramResp == nil {
						logger.Debug().Str("serial", serialNum).Msg("no parameters found for terminal")
					}
				}
				apiElapsed := time.Since(apiStart)

				// Update local database in a transaction.
				dbStart := time.Now()
				if err := h.updateLocalTerminal(ctx, serialNum, t.CSI, t.PN, t.Model, payload.AppName, termAppVersion, payload.UserName, paramResp); err != nil {
					logger.Warn().Err(err).Str("serial", serialNum).Str("csi", t.CSI).Msg("sync: failed to update local terminal")
				} else {
					atomic.AddInt64(&successCount, 1)
					paramCount := 0
					if paramResp != nil && paramResp.Data != nil {
						if pl, ok := paramResp.Data["paraList"].([]interface{}); ok {
							paramCount = len(pl)
						}
					}
					dbElapsed := time.Since(dbStart)
					logger.Info().
						Str("serial", serialNum).Str("csi", t.CSI).
						Int("params", paramCount).
						Str("api", apiElapsed.Round(time.Millisecond).String()).
						Str("db", dbElapsed.Round(time.Millisecond).String()).
						Bool("bulk", usedBulk).
						Msg("sync: terminal synced successfully")
				}

				count := atomic.AddInt64(&processedCount, 1)
				// Throttle: sleep 100-200ms every 100 terminals to avoid overwhelming TMS.
				if count%100 == 0 {
					time.Sleep(time.Duration(100+rand.Intn(101)) * time.Millisecond)
				}
				h.syncProgress(payload.UserID, int(count), totalTerminals)
			}
		}()
	}

	// Send all jobs (stop early if cancelled).
sendLoop:
	for _, t := range terminals {
		select {
		case <-cancelCh:
			break sendLoop
		case jobs <- t:
		}
	}
	close(jobs)

	// Wait for all workers to finish.
	wg.Wait()

	logger.Info().
		Str("phase2_elapsed", time.Since(phase2Start).Round(time.Millisecond).String()).
		Int64("synced", successCount).
		Int("total", totalTerminals).
		Msg("phase 2 complete: parameter fetch + DB update")

	// Check if cancelled by user.
	select {
	case <-cancelCh:
		logger.Info().Int64("synced", successCount).Int("total", totalTerminals).Str("elapsed", time.Since(jobStartTime).Round(time.Millisecond).String()).Msg("sync stopped: cancelled by user")
		return nil
	default:
	}

	if ctx.Err() != nil {
		h.adminRepo.FailPendingSyncs(payload.UserID)
		return ctx.Err()
	}

	} // end of Phase 1 & 2 (else block)

	{
		// Both full and partial modes run Phase 3 (sync all TMS terminals to local DB).
		// Phase 4 (delete stale) only runs in full mode.
		// ------------------------------------------------------------------
		// Phase 3: Ensure ALL TMS terminals exist in local DB (not just the
		// ones matching the report's app version). This fetches the full
		// terminal list from TMS and creates/updates local records.
		// ------------------------------------------------------------------
		phase3Start := time.Now()
		var err error
		allTMSCount, err = h.syncAllTMSTerminals(ctx, session, payload, syncStartTime, logger)
		if err != nil {
			logger.Warn().Err(err).Msg("failed to sync all TMS terminals")
		} else {
			logger.Info().Int64("synced_all", allTMSCount).Str("phase3_elapsed", time.Since(phase3Start).Round(time.Millisecond).String()).Msg("ensured all TMS terminals exist locally")
		}

		// ------------------------------------------------------------------
		// Phase 4: Remove terminals.
		// Full mode: delete all terminals no longer in TMS.
		// Partial mode: delete only today's deleted/rejected CSIs from local DB.
		// ------------------------------------------------------------------
		phase4Start := time.Now()
		if !payload.IsPartial {
			deleted, err = h.termRepo.DeleteStaleSynced(syncStartTime)
			if err != nil {
				logger.Warn().Err(err).Msg("failed to clean up stale terminals")
			} else if deleted > 0 {
				logger.Info().Int64("deleted", deleted).Str("phase4_elapsed", time.Since(phase4Start).Round(time.Millisecond).String()).Msg("removed stale terminals no longer in TMS")
			}
		} else {
			// Partial mode: delete today's deleted/rejected CSIs.
			deletedCSIs := h.adminRepo.FindTodayDeletedCSIs()
			logger.Info().Int("today_deleted_count", len(deletedCSIs)).Strs("csis", deletedCSIs).Msg("partial phase 4: found deleted/rejected CSIs")
			if len(deletedCSIs) > 0 {
				deleted, err = h.termRepo.DeleteBySerialNums(deletedCSIs)
				if err != nil {
					logger.Warn().Err(err).Msg("failed to clean up deleted CSIs")
				} else if deleted > 0 {
					logger.Info().Int64("deleted", deleted).Int("csis", len(deletedCSIs)).Str("phase4_elapsed", time.Since(phase4Start).Round(time.Millisecond).String()).Msg("removed today's deleted/rejected CSIs from local DB")
				}
			}
		}
	}

	// Mark sync as complete (status "3").
	h.adminRepo.CompletePendingSyncs(payload.UserID)

	logger.Info().
		Int64("synced_with_params", successCount).
		Int("report_terminals", totalTerminals).
		Int64("all_tms", allTMSCount).
		Int64("removed", deleted).
		Str("elapsed", time.Since(jobStartTime).Round(time.Millisecond).String()).
		Msg("parameter sync job completed")

	return nil
}

// syncProgress updates the sync_term_process field every 5 terminals
// to reduce database writes while still showing progress.
// Stores a percentage (0-100) so the view template can display a progress bar.
func (h *SyncParameterHandler) syncProgress(userID, current, total int) {
	if current%5 == 0 || current == total {
		pct := 0
		if total > 0 {
			pct = (current * 100) / total
		}
		process := strconv.Itoa(pct)
		h.adminRepo.UpdateSyncProcess(userID, process, "2")
	}
}

// nonPrintableRegexp matches non-printable characters (outside ASCII 0x20-0x7F).
var nonPrintableRegexp = regexp.MustCompile(`[^\x20-\x7F]`)

// isDeadlock returns true if the error is a MySQL deadlock (Error 1213).
func isDeadlock(err error) bool {
	if err == nil {
		return false
	}
	return strings.Contains(err.Error(), "1213") || strings.Contains(err.Error(), "Deadlock")
}

// updateLocalTerminal creates or updates the local terminal and its parameters.
// This closely follows the v2 SyncTerminalParameter.php process == 2 logic.
//
// Uses deadlock retry (up to 3 attempts) and batch parameter inserts to avoid
// MySQL deadlocks when 10+ concurrent workers all write to terminal_parameter.
func (h *SyncParameterHandler) updateLocalTerminal(
	ctx context.Context,
	serialNum, deviceID, productNum, model, appName, appVersion, user string,
	paramResp *tms.TMSResponse,
) error {
	const maxRetries = 3

	for attempt := 1; attempt <= maxRetries; attempt++ {
		err := h.doUpdateLocalTerminal(ctx, serialNum, deviceID, productNum, model, appName, appVersion, user, paramResp)
		if err == nil {
			return nil
		}

		// Retry on deadlock.
		if isDeadlock(err) && attempt < maxRetries {
			log.Debug().Int("attempt", attempt).Str("serial", serialNum).Msg("deadlock, retrying")
			time.Sleep(time.Duration(50*attempt) * time.Millisecond)
			continue
		}

		return err
	}
	return nil
}

// doUpdateLocalTerminal is the actual transaction logic, called by
// updateLocalTerminal with retry wrapper.
func (h *SyncParameterHandler) doUpdateLocalTerminal(
	ctx context.Context,
	serialNum, deviceID, productNum, model, appName, appVersion, user string,
	paramResp *tms.TMSResponse,
) error {
	return h.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		termRepo := terminal.NewRepository(tx)

		// Find existing terminal by term_serial_num only (CSI field) to avoid
		// cross-field collisions where one terminal's CSI matches another's SN.
		existing, _ := termRepo.FindBySerialNum(deviceID)

		now := time.Now()
		var term *terminal.Terminal

		if len(existing) > 0 {
			term = &existing[0]
			// Match V2 convention: term_serial_num = CSI name, term_device_id = hardware SN
			term.TermSerialNum = deviceID
			// Only update hardware SN if TMS returned a distinct value.
			// When serialNum is empty (TMS had SN == CSI or blank), preserve
			// the existing hardware SN already in the database.
			if serialNum != "" {
				term.TermDeviceID = serialNum
			}
			term.TermProductNum = productNum
			term.TermModel = model
			term.TermAppName = appName
			term.TermAppVersion = appVersion
			term.TermTmsUpdateOperator = &user
			term.TermTmsUpdateDtOperator = &now
			term.UpdatedBy = &user
			term.UpdatedDt = &now
			term.LastSyncedAt = &now
			if err := termRepo.Update(term); err != nil {
				return fmt.Errorf("update terminal: %w", err)
			}
		} else {
			term = &terminal.Terminal{
				// Match V2 convention: term_serial_num = CSI name, term_device_id = hardware SN
				TermDeviceID:            serialNum,
				TermSerialNum:           deviceID,
				TermProductNum:          productNum,
				TermModel:               model,
				TermAppName:             appName,
				TermAppVersion:          appVersion,
				TermTmsCreateOperator:   user,
				TermTmsCreateDtOperator: now,
				CreatedBy:               user,
				CreatedDt:               now,
				LastSyncedAt:            &now,
			}
			if err := termRepo.Create(term); err != nil {
				return fmt.Errorf("create terminal: %w", err)
			}
		}

		// Only delete and replace parameters if we have new param data from TMS.
		// This preserves existing parameters (e.g. from V2 import) when the TMS
		// API doesn't return parameters for a terminal.
		if paramResp == nil || paramResp.Data == nil {
			return nil
		}

		// Delete existing parameters before inserting fresh ones.
		// IMPORTANT: check error — if this deadlocks, the tx is dead.
		if err := tx.Where("param_term_id = ?", term.TermID).Delete(&terminal.TerminalParameter{}).Error; err != nil {
			return fmt.Errorf("delete parameters: %w", err)
		}

		paraList, ok := paramResp.Data["paraList"].([]interface{})
		if !ok || len(paraList) == 0 {
			return nil
		}

		// Build parameter maps matching v2 logic.
		hostIdx := map[int]int{}     // merchant index -> host index
		hostName := map[int]string{} // host index -> name
		merchantEnable := map[int]string{}
		merchantName := map[int]string{}
		merchantID := map[int]string{}
		terminalID := map[int]string{}
		addressIdx := map[int]int{}
		address := map[int]map[int]string{}

		for _, raw := range paraList {
			p, ok := raw.(map[string]interface{})
			if !ok {
				continue
			}
			dataName := tms.ToString(p["dataName"])
			value := tms.ToString(p["value"])

			if strings.Contains(dataName, "TP-HOST-MERCHANT_INDEX-") {
				idx := extractLastIndex(dataName)
				for _, hidx := range strings.Split(value, ",") {
					if h, err := strconv.Atoi(strings.TrimSpace(hidx)); err == nil {
						hostIdx[h] = idx
					}
				}
			}
			if strings.Contains(dataName, "TP-HOST-HOST_NAME-") {
				idx := extractLastIndex(dataName)
				hostName[idx] = value
			}
			if strings.Contains(dataName, "TP-MERCHANT-ENABLE-") {
				idx := extractLastIndex(dataName)
				merchantEnable[idx] = value
			}
			if strings.Contains(dataName, "TP-MERCHANT-MERCHANT_NAME-") {
				idx := extractLastIndex(dataName)
				merchantName[idx] = value
			}
			if strings.Contains(dataName, "TP-MERCHANT-MERCHANT_ID-") {
				idx := extractLastIndex(dataName)
				merchantID[idx] = value
			}
			if strings.Contains(dataName, "TP-MERCHANT-TERMINAL_ID-") {
				idx := extractLastIndex(dataName)
				terminalID[idx] = value
			}
			if strings.Contains(dataName, "TP-MERCHANT-PRINT_PARAM_INDEX-") {
				idx := extractLastIndex(dataName)
				if v, err := strconv.Atoi(value); err == nil {
					addressIdx[idx] = v
				}
			}
			if strings.Contains(dataName, "TP-PRINT_CONFIG-HEADER") {
				parts := strings.Split(dataName, "-")
				if len(parts) >= 2 {
					idx := extractLastIndex(dataName)
					headerField := parts[len(parts)-2]
					if len(headerField) > 0 {
						headerNum, _ := strconv.Atoi(string(headerField[len(headerField)-1]))
						if address[idx] == nil {
							address[idx] = map[int]string{}
						}
						address[idx][headerNum] = nonPrintableRegexp.ReplaceAllString(value, "")
					}
				}
			}
		}

		// Build parameter records for enabled merchants.
		// Sort merchant keys ascending to ensure deterministic insertion order
		// matching V2 (PHP iterates arrays in insertion order) and the terminal
		// device (which uses merchant index 0/1 for activation code calculation).
		var merchantKeys []int
		for key, enable := range merchantEnable {
			if enable == "1" {
				merchantKeys = append(merchantKeys, key)
			}
		}
		sort.Ints(merchantKeys)

		// Collect all params into a batch slice for a single INSERT.
		// This is much faster and avoids lock contention vs one-by-one inserts.
		var paramBatch []terminal.TerminalParameter
		for _, key := range merchantKeys {
			mid, hasMID := merchantID[key]
			tid, hasTID := terminalID[key]
			if !hasMID || !hasTID {
				continue
			}

			hostValue := hostIdx[key]
			hn := hostName[hostValue]
			mn := merchantName[key]

			param := terminal.TerminalParameter{
				ParamTermID:       term.TermID,
				ParamHostName:     hn,
				ParamMerchantName: mn,
				ParamTID:          tid,
				ParamMID:          mid,
			}

			// Set address fields.
			if addrIdx, ok := addressIdx[key]; ok {
				if addrs, ok := address[addrIdx]; ok {
					param.ParamAddress1 = safeAddrPtr(addrs[1])
					param.ParamAddress2 = safeAddrPtr(addrs[2])
					param.ParamAddress3 = safeAddrPtr(addrs[3])
					param.ParamAddress4 = safeAddrPtr(addrs[4])
					param.ParamAddress5 = safeAddrPtr(addrs[5])
					param.ParamAddress6 = safeAddrPtr(addrs[6])
				}
			}

			paramBatch = append(paramBatch, param)
		}

		// Batch insert all parameters in a single INSERT (1 lock acquisition
		// instead of N, dramatically reduces deadlock probability).
		if len(paramBatch) > 0 {
			if err := termRepo.CreateParameterBatch(paramBatch); err != nil {
				return fmt.Errorf("batch create parameters: %w", err)
			}
		}

		return nil
	})
}

// extractLastIndex extracts the last numeric index from a hyphen-separated
// parameter data name (e.g., "TP-HOST-HOST_NAME-3" -> 3).
func extractLastIndex(dataName string) int {
	parts := strings.Split(dataName, "-")
	if len(parts) == 0 {
		return 0
	}
	idx, _ := strconv.Atoi(parts[len(parts)-1])
	return idx
}

// safeAddrPtr returns a pointer to s if it is non-empty and not "null",
// otherwise nil.
func safeAddrPtr(s string) *string {
	if s == "" || s == "null" {
		return nil
	}
	return &s
}

// syncAllTMSTerminals fetches ALL terminals from TMS (regardless of app version)
// and ensures each one exists in the local database. Terminals already updated
// by Phase 2 (last_synced_at >= syncStart) are skipped.
func (h *SyncParameterHandler) syncAllTMSTerminals(
	ctx context.Context,
	session string,
	payload SyncParameterPayload,
	syncStart time.Time,
	logger zerolog.Logger,
) (int64, error) {
	// Fetch page 1 to discover totalPage.
	firstResp, err := h.tmsClient.GetTerminalListWithSize(1, 50)
	if err != nil || firstResp == nil || firstResp.Data == nil {
		return 0, fmt.Errorf("get terminal list page 1: %w", err)
	}

	totalPage := 1
	if tp, ok := firstResp.Data["totalPage"]; ok {
		if tpInt, e := strconv.Atoi(fmt.Sprintf("%v", tp)); e == nil && tpInt > 0 {
			totalPage = tpInt
		}
	}

	type tmsTerminal struct {
		DeviceID string // CSI
		SN       string
		Model    string
		Merchant string
	}

	extractFromPage := func(resp *tms.TMSResponse) []tmsTerminal {
		termList, _ := resp.Data["terminalList"].([]interface{})
		var out []tmsTerminal
		for _, t := range termList {
			tm, ok := t.(map[string]interface{})
			if !ok {
				continue
			}
			deviceID := fmt.Sprintf("%v", tm["deviceId"])
			if deviceID == "" || deviceID == "<nil>" {
				continue
			}
			out = append(out, tmsTerminal{
				DeviceID: deviceID,
				SN:       fmt.Sprintf("%v", tm["sn"]),
				Model:    fmt.Sprintf("%v", tm["model"]),
				Merchant: fmt.Sprintf("%v", tm["merchantName"]),
			})
		}
		return out
	}

	allTerminals := extractFromPage(firstResp)

	// Fetch remaining pages concurrently.
	if totalPage > 1 {
		type pageResult struct {
			Terminals []tmsTerminal
			Err       error
		}
		results := make([]pageResult, totalPage-1)
		var wg gosync.WaitGroup
		for page := 2; page <= totalPage; page++ {
			wg.Add(1)
			go func(p int) {
				defer wg.Done()
				resp, err := h.tmsClient.GetTerminalListWithSize(p, 50)
				idx := p - 2
				if err != nil || resp == nil || resp.Data == nil {
					results[idx] = pageResult{Err: err}
					return
				}
				results[idx] = pageResult{Terminals: extractFromPage(resp)}
			}(page)
		}
		wg.Wait()

		for _, pr := range results {
			if pr.Err == nil {
				allTerminals = append(allTerminals, pr.Terminals...)
			}
		}
	}

	logger.Info().Int("tms_total", len(allTerminals)).Msg("fetched all TMS terminals for local sync")

	// Upsert each terminal that wasn't already touched by Phase 2.
	// Use a concurrent worker pool (20 workers) since these are DB-only
	// operations (no API calls), much faster than the sequential loop.
	const phase3Workers = 20
	var count int64
	now := time.Now()

	p3jobs := make(chan tmsTerminal, len(allTerminals))
	var p3wg gosync.WaitGroup

	for w := 0; w < phase3Workers; w++ {
		p3wg.Add(1)
		go func() {
			defer p3wg.Done()
			for t := range p3jobs {
				select {
				case <-ctx.Done():
					return
				default:
				}

				err := h.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
					termRepo := terminal.NewRepository(tx)

					// Search by term_serial_num only (CSI field) to avoid collisions.
					existing, _ := termRepo.FindBySerialNum(t.DeviceID)
					if len(existing) > 0 {
						term := &existing[0]
						// Already up to date from Phase 2 — skip.
						if term.LastSyncedAt != nil && !term.LastSyncedAt.Before(syncStart) {
							return nil
						}
						// Only update hardware SN if TMS returned a distinct value
						// (not empty, not "<nil>", and not the same as the CSI name).
						// When TMS returns SN == CSI (common for imported terminals),
						// preserve the existing hardware SN in the database.
						if t.SN != "" && t.SN != "<nil>" && t.SN != t.DeviceID {
							term.TermDeviceID = t.SN
						}
						term.TermSerialNum = t.DeviceID
						term.TermModel = t.Model
						term.LastSyncedAt = &now
						user := payload.UserName
						term.UpdatedBy = &user
						term.UpdatedDt = &now
						return termRepo.Update(term)
					}

					// Create new terminal.
					sn := t.SN
					if sn == "<nil>" || sn == t.DeviceID {
						sn = ""
					}
					newTerm := &terminal.Terminal{
						TermDeviceID:            sn,
						TermSerialNum:           t.DeviceID,
						TermModel:               t.Model,
						TermTmsCreateOperator:   payload.UserName,
						TermTmsCreateDtOperator: now,
						CreatedBy:               payload.UserName,
						CreatedDt:               now,
						LastSyncedAt:            &now,
					}
					return termRepo.Create(newTerm)
				})
				if err != nil {
					logger.Debug().Err(err).Str("csi", t.DeviceID).Msg("failed to sync TMS terminal")
				} else {
					atomic.AddInt64(&count, 1)
				}
			}
		}()
	}

	for _, t := range allTerminals {
		p3jobs <- t
	}
	close(p3jobs)
	p3wg.Wait()

	return count, nil
}
