package queue

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"regexp"
	"strconv"
	"strings"
	gosync "sync"
	"sync/atomic"
	"time"

	"github.com/hibiken/asynq"
	"github.com/rs/zerolog/log"
	"github.com/xuri/excelize/v2"
	"gorm.io/gorm"

	"github.com/verifone/veristoretools3/internal/admin"
	"github.com/verifone/veristoretools3/internal/terminal"
	"github.com/verifone/veristoretools3/internal/tms"
)

const (
	// syncWorkerCount is the number of concurrent workers for fetching
	// terminal parameters. Each worker makes 1 API call per terminal.
	syncWorkerCount = 50
)

// SyncParameterPayload is the JSON payload for the sync:parameter task.
// Chained from report:terminal when TriggerSync is true (Sekarang button).
type SyncParameterPayload struct {
	ReportName string `json:"report_name"`
	Session    string `json:"session"`
	UserID     int    `json:"user_id"`
	UserName   string `json:"user_name"`
	AppID      string `json:"app_id"`
	AppName    string `json:"app_name"`
	AppVersion string `json:"app_version"`
}

// syncTerminalRow holds data parsed from one row of the Excel report.
type syncTerminalRow struct {
	Index      int
	CSI        string // Column A (deviceId / serial num used as key)
	SN         string // Column B
	PN         string // Column C
	Model      string // Column D
	Merchant   string // Column E
	AppVersion string // Column G (actual installed version per terminal)
	AppID      string // Column H (appId for this terminal's version)
}

// SyncParameterHandler reads the Excel report generated by report:terminal,
// fetches terminal parameters from the TMS API for each terminal, and updates
// the local terminal and terminal_parameter tables. This is the Go equivalent
// of veristoreTools2's SyncTerminalParameter.php component, optimized with a
// 50-worker concurrent pool instead of V2's sequential approach.
type SyncParameterHandler struct {
	tmsService *tms.Service
	tmsClient  *tms.Client
	termRepo   *terminal.Repository
	adminRepo  *admin.Repository
	db         *gorm.DB
}

// NewSyncParameterHandler creates a new handler for the sync:parameter task.
func NewSyncParameterHandler(
	tmsService *tms.Service,
	tmsClient *tms.Client,
	termRepo *terminal.Repository,
	adminRepo *admin.Repository,
	_ interface{}, // syncRepo — kept for backward-compatible constructor signature
	db *gorm.DB,
	_ int, // batchSize — no longer used
) *SyncParameterHandler {
	return &SyncParameterHandler{
		tmsService: tmsService,
		tmsClient:  tmsClient,
		termRepo:   termRepo,
		adminRepo:  adminRepo,
		db:         db,
	}
}

// ProcessTask implements asynq.Handler. It:
//  1. Reads the Excel report from the tms_report table.
//  2. Parses terminal rows from the spreadsheet.
//  3. For each terminal, fetches parameters from TMS via a 50-worker pool.
//  4. Updates the local terminal and terminal_parameter tables.
//  5. Updates sync_terminal progress and marks complete.
func (h *SyncParameterHandler) ProcessTask(ctx context.Context, task *asynq.Task) error {
	var payload SyncParameterPayload
	if err := json.Unmarshal(task.Payload(), &payload); err != nil {
		return fmt.Errorf("sync_parameter: unmarshal payload: %w", err)
	}

	logger := log.With().Str("task", TaskSyncParameter).Str("report", payload.ReportName).Logger()
	logger.Info().Msg("starting parameter sync job")

	// Log job start to queue_log.
	createTime := strconv.FormatInt(time.Now().UnixMilli(), 10)
	_ = h.adminRepo.CreateQueueLog(&admin.QueueLog{
		CreateTime:  createTime,
		ExecTime:    createTime,
		ProcessName: "SYNC",
		ServiceName: strPtr("sync:parameter"),
	})

	session := payload.Session
	if session == "" {
		session = h.tmsService.GetSession()
	}
	if session == "" {
		h.adminRepo.FailPendingSyncs(payload.UserID)
		return fmt.Errorf("sync_parameter: no active TMS session")
	}

	// ------------------------------------------------------------------
	// Phase 1: Read Excel report from tms_report table.
	// ------------------------------------------------------------------
	report, err := h.adminRepo.FindTmsReportByName(payload.ReportName)
	if err != nil || report == nil {
		h.adminRepo.FailPendingSyncs(payload.UserID)
		return fmt.Errorf("sync_parameter: report not found: %s: %w", payload.ReportName, err)
	}

	if len(report.TmsRptFile) == 0 {
		h.adminRepo.FailPendingSyncs(payload.UserID)
		return fmt.Errorf("sync_parameter: report file is empty: %s", payload.ReportName)
	}

	// Parse the Excel file.
	f, err := excelize.OpenReader(bytes.NewReader(report.TmsRptFile))
	if err != nil {
		h.adminRepo.FailPendingSyncs(payload.UserID)
		return fmt.Errorf("sync_parameter: open excel: %w", err)
	}
	defer f.Close()

	// Get the first sheet name.
	sheetName := f.GetSheetName(0)
	if sheetName == "" {
		h.adminRepo.FailPendingSyncs(payload.UserID)
		return fmt.Errorf("sync_parameter: no sheets in excel")
	}

	// Parse appID from row 1 cell A1 ("APPID:{id}").
	appID := payload.AppID
	if appID == "" {
		a1, _ := f.GetCellValue(sheetName, "A1")
		if strings.HasPrefix(a1, "APPID:") {
			appID = strings.TrimPrefix(a1, "APPID:")
		}
	}

	// Read all rows. Row 1 = APPID header, Row 2 = column headers, Row 3+ = data.
	allRows, err := f.GetRows(sheetName)
	if err != nil {
		h.adminRepo.FailPendingSyncs(payload.UserID)
		return fmt.Errorf("sync_parameter: read rows: %w", err)
	}

	var terminals []syncTerminalRow
	for i, row := range allRows {
		if i < 2 { // Skip header rows
			continue
		}
		if len(row) < 2 { // Need at least CSI and SN
			continue
		}

		csi := ""
		sn := ""
		pn := ""
		model := ""
		merchant := ""
		appVersion := ""
		termAppID := ""
		if len(row) > 0 {
			csi = strings.TrimSpace(row[0])
		}
		if len(row) > 1 {
			sn = strings.TrimSpace(row[1])
		}
		if len(row) > 2 {
			pn = strings.TrimSpace(row[2])
		}
		if len(row) > 3 {
			model = strings.TrimSpace(row[3])
		}
		if len(row) > 4 {
			merchant = strings.TrimSpace(row[4])
		}
		// Column G: per-terminal AppVersion, Column H: per-terminal AppID
		if len(row) > 6 {
			appVersion = strings.TrimSpace(row[6])
		}
		if len(row) > 7 {
			termAppID = strings.TrimSpace(row[7])
		}

		if sn == "" && csi == "" {
			continue
		}

		terminals = append(terminals, syncTerminalRow{
			Index:      len(terminals),
			CSI:        csi,
			SN:         sn,
			PN:         pn,
			Model:      model,
			Merchant:   merchant,
			AppVersion: appVersion,
			AppID:      termAppID,
		})
	}

	totalTerminals := len(terminals)
	logger.Info().Int("total_terminals", totalTerminals).Str("sheet", sheetName).Msg("parsed Excel report")

	if totalTerminals == 0 {
		logger.Warn().Msg("no terminals in report, completing sync")
		h.adminRepo.CompletePendingSyncs(payload.UserID)
		return nil
	}

	// ------------------------------------------------------------------
	// Phase 2: Fetch parameters and update local DB using worker pool.
	// Uses incremental create/update per terminal.
	// Each terminal's parameters are deleted and recreated individually
	// inside updateLocalTerminal.
	// Phase 3 (after workers finish) removes any local terminals
	// that are no longer in the TMS report (e.g. deleted from TMS).
	// ------------------------------------------------------------------
	tabNames := tms.GetAllTabNames(h.db)
	jobs := make(chan syncTerminalRow, totalTerminals)
	var processedCount int64
	var successCount int64
	var wg gosync.WaitGroup

	for w := 0; w < syncWorkerCount; w++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for t := range jobs {
				select {
				case <-ctx.Done():
					return
				default:
				}

				serialNum := t.SN
				if serialNum == "" {
					serialNum = t.CSI
				}

				// Use per-terminal AppID if available (from Excel column H),
				// otherwise fall back to the report-level appID.
				termAppID := t.AppID
				if termAppID == "" || termAppID == "0" || termAppID == "<nil>" {
					termAppID = appID
				}

				// Use per-terminal AppVersion if available (from Excel column G),
				// otherwise fall back to the payload version.
				termAppVersion := t.AppVersion
				if termAppVersion == "" || termAppVersion == "<nil>" {
					termAppVersion = payload.AppVersion
				}

				// Fetch terminal parameters from TMS (1 API call).
				var paramResp *tms.TMSResponse
				if termAppID != "" && serialNum != "" {
					resp, err := h.tmsClient.GetTerminalParameterMultiTab(session, serialNum, termAppID, tabNames)
					if err == nil && resp != nil && resp.ResultCode == 0 && resp.Data != nil {
						if pl, ok := resp.Data["paraList"].([]interface{}); ok && len(pl) > 0 {
							paramResp = resp
						}
					}
					if paramResp == nil {
						logger.Debug().Str("serial", serialNum).Msg("no parameters found for terminal")
					}
				}

				// Update local database in a transaction.
				if err := h.updateLocalTerminal(ctx, serialNum, t.CSI, t.PN, t.Model, payload.AppName, termAppVersion, payload.UserName, paramResp); err != nil {
					logger.Warn().Err(err).Str("serial", serialNum).Msg("failed to update local terminal")
				} else {
					atomic.AddInt64(&successCount, 1)
				}

				count := atomic.AddInt64(&processedCount, 1)
				h.syncProgress(payload.UserID, int(count), totalTerminals)
			}
		}()
	}

	// Send all jobs.
	for _, t := range terminals {
		jobs <- t
	}
	close(jobs)

	// Wait for all workers to finish.
	wg.Wait()

	if ctx.Err() != nil {
		h.adminRepo.FailPendingSyncs(payload.UserID)
		return ctx.Err()
	}

	// Mark sync as complete (status "3").
	h.adminRepo.CompletePendingSyncs(payload.UserID)

	logger.Info().
		Int64("synced", successCount).
		Int("total", totalTerminals).
		Msg("parameter sync job completed")

	return nil
}

// syncProgress updates the sync_term_process field every 5 terminals
// to reduce database writes while still showing progress.
// Stores a percentage (0-100) so the view template can display a progress bar.
func (h *SyncParameterHandler) syncProgress(userID, current, total int) {
	if current%5 == 0 || current == total {
		pct := 0
		if total > 0 {
			pct = (current * 100) / total
		}
		process := strconv.Itoa(pct)
		h.adminRepo.UpdateSyncProcess(userID, process, "2")
	}
}

// nonPrintableRegexp matches non-printable characters (outside ASCII 0x20-0x7F).
var nonPrintableRegexp = regexp.MustCompile(`[^\x20-\x7F]`)

// updateLocalTerminal creates or updates the local terminal and its parameters.
// This closely follows the v2 SyncTerminalParameter.php process == 2 logic.
func (h *SyncParameterHandler) updateLocalTerminal(
	ctx context.Context,
	serialNum, deviceID, productNum, model, appName, appVersion, user string,
	paramResp *tms.TMSResponse,
) error {
	return h.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		termRepo := terminal.NewRepository(tx)

		// Find existing terminal or create a new one.
		existing, _ := termRepo.FindByCSI(serialNum)

		now := time.Now()
		var term *terminal.Terminal

		if len(existing) > 0 {
			term = &existing[0]
			term.TermDeviceID = deviceID
			term.TermProductNum = productNum
			term.TermModel = model
			term.TermAppName = appName
			term.TermAppVersion = appVersion
			term.TermTmsUpdateOperator = &user
			term.TermTmsUpdateDtOperator = &now
			term.UpdatedBy = &user
			term.UpdatedDt = &now
			if err := termRepo.Update(term); err != nil {
				return fmt.Errorf("update terminal: %w", err)
			}
		} else {
			term = &terminal.Terminal{
				TermDeviceID:            deviceID,
				TermSerialNum:           serialNum,
				TermProductNum:          productNum,
				TermModel:               model,
				TermAppName:             appName,
				TermAppVersion:          appVersion,
				TermTmsCreateOperator:   user,
				TermTmsCreateDtOperator: now,
				CreatedBy:               user,
				CreatedDt:               now,
			}
			if err := termRepo.Create(term); err != nil {
				return fmt.Errorf("create terminal: %w", err)
			}
		}

		// Delete existing parameters for this terminal.
		tx.Where("param_term_id = ?", term.TermID).Delete(&terminal.TerminalParameter{})

		// Parse and insert new parameters if we have param data.
		if paramResp == nil || paramResp.Data == nil {
			return nil
		}

		paraList, ok := paramResp.Data["paraList"].([]interface{})
		if !ok || len(paraList) == 0 {
			return nil
		}

		// Build parameter maps matching v2 logic.
		hostIdx := map[int]int{}     // merchant index -> host index
		hostName := map[int]string{} // host index -> name
		merchantEnable := map[int]string{}
		merchantName := map[int]string{}
		merchantID := map[int]string{}
		terminalID := map[int]string{}
		addressIdx := map[int]int{}
		address := map[int]map[int]string{}

		for _, raw := range paraList {
			p, ok := raw.(map[string]interface{})
			if !ok {
				continue
			}
			dataName := tms.ToString(p["dataName"])
			value := tms.ToString(p["value"])

			if strings.Contains(dataName, "TP-HOST-MERCHANT_INDEX-") {
				idx := extractLastIndex(dataName)
				for _, hidx := range strings.Split(value, ",") {
					if h, err := strconv.Atoi(strings.TrimSpace(hidx)); err == nil {
						hostIdx[h] = idx
					}
				}
			}
			if strings.Contains(dataName, "TP-HOST-HOST_NAME-") {
				idx := extractLastIndex(dataName)
				hostName[idx] = value
			}
			if strings.Contains(dataName, "TP-MERCHANT-ENABLE-") {
				idx := extractLastIndex(dataName)
				merchantEnable[idx] = value
			}
			if strings.Contains(dataName, "TP-MERCHANT-MERCHANT_NAME-") {
				idx := extractLastIndex(dataName)
				merchantName[idx] = value
			}
			if strings.Contains(dataName, "TP-MERCHANT-MERCHANT_ID-") {
				idx := extractLastIndex(dataName)
				merchantID[idx] = value
			}
			if strings.Contains(dataName, "TP-MERCHANT-TERMINAL_ID-") {
				idx := extractLastIndex(dataName)
				terminalID[idx] = value
			}
			if strings.Contains(dataName, "TP-MERCHANT-PRINT_PARAM_INDEX-") {
				idx := extractLastIndex(dataName)
				if v, err := strconv.Atoi(value); err == nil {
					addressIdx[idx] = v
				}
			}
			if strings.Contains(dataName, "TP-PRINT_CONFIG-HEADER") {
				parts := strings.Split(dataName, "-")
				if len(parts) >= 2 {
					idx := extractLastIndex(dataName)
					headerField := parts[len(parts)-2]
					if len(headerField) > 0 {
						headerNum, _ := strconv.Atoi(string(headerField[len(headerField)-1]))
						if address[idx] == nil {
							address[idx] = map[int]string{}
						}
						address[idx][headerNum] = nonPrintableRegexp.ReplaceAllString(value, "")
					}
				}
			}
		}

		// Create terminal parameter records for enabled merchants.
		for key, enable := range merchantEnable {
			if enable != "1" {
				continue
			}
			mid, hasMID := merchantID[key]
			tid, hasTID := terminalID[key]
			if !hasMID || !hasTID {
				continue
			}

			hostValue := hostIdx[key]
			hn := hostName[hostValue]
			mn := merchantName[key]

			param := &terminal.TerminalParameter{
				ParamTermID:       term.TermID,
				ParamHostName:     hn,
				ParamMerchantName: mn,
				ParamTID:          tid,
				ParamMID:          mid,
			}

			// Set address fields.
			if addrIdx, ok := addressIdx[key]; ok {
				if addrs, ok := address[addrIdx]; ok {
					param.ParamAddress1 = safeAddrPtr(addrs[1])
					param.ParamAddress2 = safeAddrPtr(addrs[2])
					param.ParamAddress3 = safeAddrPtr(addrs[3])
					param.ParamAddress4 = safeAddrPtr(addrs[4])
					param.ParamAddress5 = safeAddrPtr(addrs[5])
					param.ParamAddress6 = safeAddrPtr(addrs[6])
				}
			}

			if err := termRepo.CreateParameter(param); err != nil {
				log.Warn().Err(err).Str("serial", serialNum).Msg("failed to create terminal parameter")
			}
		}

		return nil
	})
}

// extractLastIndex extracts the last numeric index from a hyphen-separated
// parameter data name (e.g., "TP-HOST-HOST_NAME-3" -> 3).
func extractLastIndex(dataName string) int {
	parts := strings.Split(dataName, "-")
	if len(parts) == 0 {
		return 0
	}
	idx, _ := strconv.Atoi(parts[len(parts)-1])
	return idx
}

// safeAddrPtr returns a pointer to s if it is non-empty and not "null",
// otherwise nil.
func safeAddrPtr(s string) *string {
	if s == "" || s == "null" {
		return nil
	}
	return &s
}
